version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "eu-central-1"
    ECR_REPOSITORY_URI: "123456789012.dkr.ecr.eu-central-1.amazonaws.com"
    IMAGE_NAME: "demo-pipeline"
    IMAGE_TAG: 1.0

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - printenv > .env
  build:
    commands:
      - docker build -t $IMAGE_NAME --target worker --tag $ECR_REPOSITORY_URI:latest .
  post_build:
    commands:
      - docker tag $ECR_REPOSITORY_URI:latest $ECR_REPOSITORY_URI:$IMAGE_TAG
      - docker push $ECR_REPOSITORY_URI:latest
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
      - printf "[{\"name\":\"${IMAGE_NAME}\",\"imageUri\":\"${ECR_REPOSITORY_URI}:${IMAGE_TAG}\"}]" > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes
