---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-app
  labels:
    app: httpbin-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: httpbin